#!/usr/bin/env bash
#comment
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Assign the first argument to IP variable
IP=$1

# Ping the IP 5 times
ping -c 5 "$IP"
